// This file will be auto-generated by: supabase gen types typescript
// For now, we define the basic structure manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'estudiante' | 'apoderado' | 'admin'
export type GradeLevel = '5_basico' | '6_basico' | '7_basico' | '8_basico' | '1_medio' | '2_medio' | '3_medio' | '4_medio'
export type EnrollmentStatus = 'pendiente' | 'activa' | 'suspendida' | 'cancelada' | 'completada'
export type PaymentStatus = 'pendiente' | 'pagado' | 'fallido' | 'reembolsado' | 'vencido'
export type PaymentMethod = 'transbank' | 'khipu' | 'transferencia_manual'
export type LessonType = 'video' | 'texto' | 'mixto'
export type QuestionType = 'opcion_multiple' | 'verdadero_falso' | 'completar' | 'ordenar' | 'asociar'
export type AdaptivePath = 'refuerzo' | 'normal' | 'desafio'
export type ContentGenStatus = 'pendiente' | 'generando' | 'revision' | 'aprobado' | 'rechazado'
export type NotificationType = 'pago_pendiente' | 'pago_confirmado' | 'pago_fallido' | 'progreso_bajo' | 'logro_obtenido' | 'leccion_completada' | 'quiz_completado' | 'repaso_pendiente' | 'matricula_aprobada'
export type ReviewRating = 'again' | 'hard' | 'good' | 'easy'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          role: UserRole
          email: string
          full_name: string
          rut: string | null
          phone: string | null
          avatar_url: string | null
          grade_level: GradeLevel | null
          parent_id: string | null
          is_active: boolean
          onboarding_completed: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          role?: UserRole
          email: string
          full_name: string
          rut?: string | null
          phone?: string | null
          avatar_url?: string | null
          grade_level?: GradeLevel | null
          parent_id?: string | null
          is_active?: boolean
          onboarding_completed?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role?: UserRole
          email?: string
          full_name?: string
          rut?: string | null
          phone?: string | null
          avatar_url?: string | null
          grade_level?: GradeLevel | null
          parent_id?: string | null
          is_active?: boolean
          onboarding_completed?: boolean
          updated_at?: string
        }
      }
      subjects: {
        Row: {
          id: string
          name: string
          slug: string
          icon_url: string | null
          color: string | null
          display_order: number
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          icon_url?: string | null
          color?: string | null
          display_order?: number
          created_at?: string
        }
        Update: {
          name?: string
          slug?: string
          icon_url?: string | null
          color?: string | null
          display_order?: number
        }
      }
      courses: {
        Row: {
          id: string
          subject_id: string
          grade_level: GradeLevel
          title: string
          slug: string
          description: string | null
          thumbnail_url: string | null
          is_published: boolean
          total_units: number
          total_lessons: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          subject_id: string
          grade_level: GradeLevel
          title: string
          slug: string
          description?: string | null
          thumbnail_url?: string | null
          is_published?: boolean
          total_units?: number
          total_lessons?: number
        }
        Update: {
          subject_id?: string
          grade_level?: GradeLevel
          title?: string
          slug?: string
          description?: string | null
          thumbnail_url?: string | null
          is_published?: boolean
          total_units?: number
          total_lessons?: number
        }
      }
      units: {
        Row: {
          id: string
          course_id: string
          title: string
          slug: string
          description: string | null
          display_order: number
          is_published: boolean
          total_lessons: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          course_id: string
          title: string
          slug: string
          description?: string | null
          display_order: number
          is_published?: boolean
          total_lessons?: number
        }
        Update: {
          title?: string
          slug?: string
          description?: string | null
          display_order?: number
          is_published?: boolean
          total_lessons?: number
        }
      }
      lessons: {
        Row: {
          id: string
          unit_id: string
          title: string
          slug: string
          lesson_type: LessonType
          display_order: number
          is_published: boolean
          video_url: string | null
          video_duration_seconds: number | null
          content_html: string | null
          summary_pdf_url: string | null
          difficulty_level: number
          estimated_minutes: number
          prerequisites: Json
          reinforcement_content_html: string | null
          reinforcement_video_url: string | null
          challenge_content_html: string | null
          challenge_project_description: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          unit_id: string
          title: string
          slug: string
          lesson_type?: LessonType
          display_order: number
          is_published?: boolean
          video_url?: string | null
          video_duration_seconds?: number | null
          content_html?: string | null
          summary_pdf_url?: string | null
          difficulty_level?: number
          estimated_minutes?: number
          prerequisites?: Json
          reinforcement_content_html?: string | null
          reinforcement_video_url?: string | null
          challenge_content_html?: string | null
          challenge_project_description?: string | null
        }
        Update: {
          title?: string
          slug?: string
          lesson_type?: LessonType
          display_order?: number
          is_published?: boolean
          video_url?: string | null
          video_duration_seconds?: number | null
          content_html?: string | null
          summary_pdf_url?: string | null
          difficulty_level?: number
          estimated_minutes?: number
          prerequisites?: Json
          reinforcement_content_html?: string | null
          reinforcement_video_url?: string | null
          challenge_content_html?: string | null
          challenge_project_description?: string | null
        }
      }
      quizzes: {
        Row: {
          id: string
          lesson_id: string
          title: string
          description: string | null
          passing_score: number
          time_limit_seconds: number | null
          max_attempts: number
          shuffle_questions: boolean
          shuffle_options: boolean
          show_correct_after: boolean
          is_published: boolean
          total_questions: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          lesson_id: string
          title: string
          description?: string | null
          passing_score?: number
          time_limit_seconds?: number | null
          max_attempts?: number
          shuffle_questions?: boolean
          shuffle_options?: boolean
          show_correct_after?: boolean
          is_published?: boolean
          total_questions?: number
        }
        Update: {
          title?: string
          description?: string | null
          passing_score?: number
          time_limit_seconds?: number | null
          max_attempts?: number
          shuffle_questions?: boolean
          shuffle_options?: boolean
          show_correct_after?: boolean
          is_published?: boolean
          total_questions?: number
        }
      }
      questions: {
        Row: {
          id: string
          quiz_id: string
          question_type: QuestionType
          question_text: string
          question_image_url: string | null
          display_order: number
          points: number
          difficulty_level: number
          topic_tag: string | null
          options: Json
          correct_answer: Json
          feedback_correct: string
          feedback_incorrect: string
          feedback_hint: string | null
          feedback_per_option: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          quiz_id: string
          question_type?: QuestionType
          question_text: string
          question_image_url?: string | null
          display_order: number
          points?: number
          difficulty_level?: number
          topic_tag?: string | null
          options: Json
          correct_answer: Json
          feedback_correct: string
          feedback_incorrect: string
          feedback_hint?: string | null
          feedback_per_option?: Json
        }
        Update: {
          question_type?: QuestionType
          question_text?: string
          question_image_url?: string | null
          display_order?: number
          points?: number
          difficulty_level?: number
          topic_tag?: string | null
          options?: Json
          correct_answer?: Json
          feedback_correct?: string
          feedback_incorrect?: string
          feedback_hint?: string | null
          feedback_per_option?: Json
        }
      }
      student_stats: {
        Row: {
          id: string
          student_id: string
          total_xp: number
          current_level: number
          current_streak: number
          longest_streak: number
          total_lessons_completed: number
          total_quizzes_completed: number
          total_time_seconds: number
          average_quiz_score: number
          last_activity_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          student_id: string
          total_xp?: number
          current_level?: number
          current_streak?: number
          longest_streak?: number
          total_lessons_completed?: number
          total_quizzes_completed?: number
          total_time_seconds?: number
          average_quiz_score?: number
          last_activity_date?: string | null
        }
        Update: {
          total_xp?: number
          current_level?: number
          current_streak?: number
          longest_streak?: number
          total_lessons_completed?: number
          total_quizzes_completed?: number
          total_time_seconds?: number
          average_quiz_score?: number
          last_activity_date?: string | null
        }
      }
      // Add remaining table types as needed when auto-generated
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_adaptive_path: {
        Args: {
          p_lesson_id: string
          p_score_percent: number
        }
        Returns: Json
      }
      calculate_streak: {
        Args: {
          p_student_id: string
        }
        Returns: number
      }
    }
    Enums: {
      user_role: UserRole
      grade_level: GradeLevel
      enrollment_status: EnrollmentStatus
      payment_status: PaymentStatus
      payment_method: PaymentMethod
      lesson_type: LessonType
      question_type: QuestionType
      adaptive_path: AdaptivePath
      content_gen_status: ContentGenStatus
      notification_type: NotificationType
      review_rating: ReviewRating
    }
  }
}
